
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
# for offset=0. speed_to_erpm_gain = num_motor_poles*60/circumference_wheel_in_meters
speed_to_erpm_gain: 4200
speed_to_erpm_offset: 0.0

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 100.0 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 9 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: 0.8
steering_angle_to_servo_offset: 0.48

# publish odom to base link tf
vesc_to_odom/publish_tf: false

# car wheelbase is about 25cm 
wheelbase: .25

vesc_driver:
  port: /dev/sensors/vesc
  duty_cycle_min: -0.3
  duty_cycle_max: 0.3
  current_min: 0.0
  current_max: 20.0
  brake_min: -20000.0
  brake_max: 200000.0
  speed_min: -10000
  speed_max: 40000
  position_min: 0.0
  position_max: 0.0
  servo_min: 0
  servo_max: 1
